### ISSUE TITLE
Comment télécharger les données ?

### ISSUE THREAD

**Issue by bgoglin** [JC144/EDF_Simulateur_Prix#1]
Bonjour
Pourriez-vous documenter comment récupérer les données sur le site equilibre.edf ? Le ZIP que je récupère ne contient pas le fichier avec le nom que votre index.html demande, et aucun des fichiers ne semble contenit les données toutes les 30mn. Est-ce qu'il faut activer quelque chose dans mon compte ?
Merci bien

**Comment by JC144** [comment]
Bonjour,

Depuis le site [d'EDF](https://particulier.edf.fr)

Cliquez sur + De détails dans la partie "Ma consommation d’électricité"
![EDF1](https://user-images.githubusercontent.com/1168432/216930308-0523e260-e788-44b5-a4aa-d0df4d25e3d3.png)

Vous serez redirigés vers le site [d'équilibre edf](https://equilibre.edf.fr)

Cliquez sur "télécharger mes données" un peu plus bas sur la page
![EDF21](https://user-images.githubusercontent.com/1168432/216930725-d3af991d-7761-40bc-892f-285d11390fd8.png)

Il faut peut-être activer le suivi à la demi-heure, mais je ne sais pas exactement où cela se trouve.
