### ISSUE TITLE
Les tarif par mois non reel si l'import est de moins d'un an

### ISSUE THREAD

**Issue by 10tribu** [JC144/EDF_Simulateur_Prix#12]
Bonjour,
Lorsque j'importe mes données (qui ne sont que de 7 mois)
le résultat (XX,XX €/mois) sur l'estimation et la différence, n'est pas bon... 
car calculer sur 12 mois :
`((result.tarif.price - resultsOrdered[0].tarif.price) / **12**).toFixed(2)
(result.tarif.price / **12**).toFixed(2)
`
il faudrai je pense faire un calcul : 
(monthBeginSelector yearBeginSelector) - (monthEndSelector yearEndSelector ) = monthDiff
pour avoir le nombre de mois entre ces 2 dates et l'utiliser pour diviser le cout / mois.

Merci encore pour ce super outil

**Comment by JC144** [comment]
Fixé !
Merci pour le retour
