### ISSUE TITLE
Problème total énergie

### ISSUE THREAD

**Issue by Trichelieu62** [JC144/EDF_Simulateur_Prix#18]
Bonjour,
Merci pour ce bel outil !
Je rencontre un petit souci avec le csv total énergie, toutes les données en kwh sont divisées par 2 (exemple sur un jour 2023/01/26 : simulateur = 13.18kWh, dans le CSV = 26,357, sur site Enedis = 26.6)
Bon week end !

**Comment by JC144** [comment]
Merci pour le retour, juste pour clarifier, les données sont bonnes au niveau du CSV provenant de Total Energie mais pas dans le simulateur ?

@jo-sarrazin est-ce que vous avez une idée ?

**Comment by jo-sarrazin** [comment]
Je vais voir d'où viens le problème, cependant j'ai bien les bonnes valeurs en sortie de parser, peut-être que je ne renvoie pas les données horaires de la manière attendue pour le calcul ?

**Comment by Trichelieu62** [comment]
Effectivement les données du CSV sont bonnes mais une fois intégrées dans le simulateur non, peut être effectivement que dans le CSV 1 ligne = 30 min et dans le simulateur 1 ligne = 1h ?

**Comment by JC144** [comment]
J'ai poussé une version sur la branche de dev pour gérer des paliers autres que la demi-heure. Entre autres, pour gérer ceux au quart d'heure d'Enedis.

Si l'un de vous peut tester sur ses données.

**Comment by JC144** [comment]
Sur les deux branches on a quelques centimes de différences sur le réel de Tempo, je vais créer une issue.

**Comment by jo-sarrazin** [comment]
> J'ai poussé une version sur la branche de dev pour gérer des paliers autres que la demi-heure. Entre autres, pour gérer ceux au quart d'heure d'Enedis.
> 
> Si l'un de vous peut tester sur ses données.

A priori le problème est toujours présent, je peux passer en demie-heure ou laisser la somme horaire, dans tous les cas ça reste divisé par 2 dans le simulateur, alors que les données prennent bien tout en compte.

Une idée de pourquoi un divisé par 2 a été mis ici dans calculator.js :
`hourData.conso = (parseInt(data[day].hours[hour][1]) + parseInt(data[day].hours[hour + 1][1])) / 2;`

**Comment by JC144** [comment]
J'ai poussé sur la branche Dev. Je pense que le problème venait de ça en
effet, je prends toutes les tranches de la même heure maintenant.

**Comment by jo-sarrazin** [comment]
> J'ai poussé sur la branche Dev. Je pense que le problème venait de ça en effet, je prends toutes les tranches de la même heure maintenant.

Avec la modification de la branche Dev, j'ai ces résultats :
- si je reste avec une somme horaire, la consommation semble bonne mais ça ne pas prendre la dernière tranche (donc ici la somme de 23h et 23h30)
- si je passe en demie-heure, ça me laisse la consommation divisée par 2 et ça ne prends pas la dernière tranche (23h30)

**Comment by g-laures** [comment]
En effet cela semble fonctionner, merci.
