### ISSUE TITLE
Possibilité de saisir les plages horaires HC/HP

### ISSUE THREAD

**Issue by mxmrlt** [JC144/EDF_Simulateur_Prix#2]
Il serait intéressant de pouvoir paramétrer ses heures creuses et pleines au même titre que la puissance souscrite.

Par exemple, le mien avec tarif bleu et deux plages horaires bien distinctes pour les heures creuses :
HC : 1h34 -> 7h34 / 12h34 -> 14h34
HP : le reste du temps

L'impact et la stratégie quant au chauffage et autre peut être non négligeable.

Merci.

**Comment by xavax59** [comment]
Bonjour, J'ai exactement la meme demande, aujourd'hui j'ai un abonnement HC HP avec 2 plages D'heures creuses. une la nuit et une seconde le midi. Ca serait top que l'outil puisse en tenir compte. 
Merci beaucoup pour cet outil

**Comment by JC144** [comment]
Je devrais pouvoir faire quelque chose, techniquement le code le permet.

On est sur le tarif bleu heures creuses.
On veut pouvoir customiser max trois plages HC (ex: 22h00-23h59, 00h00-06h00, 15h00-17h00).
Un peu comme la sélection du jour sobriété pour le tarif Zen ?

**Comment by mxmrlt** [comment]
Oui.

Pourquoi pas jusqu'à 3 plages. Mais avec deux listes déroulantes pour chaque plage horaire (début et fin) ?

**Comment by JC144** [comment]
Bonne idée les listes déroulantes, j'étais en train de tester avec un range picker custom.

Question, on est sur des heures entières ou ça peut aller à la demi-heure ?

**Comment by mxmrlt** [comment]
Il faut aller à la demi-heure si je prends mon cas. 1h34 -> 7h34 / 12h34 -> 14h34

Mais on peut évidemment oublier les minutes dans la mesure où les exports Enedis ou EDF n'en tiennent pas compte.
Ce qui donnerait 1h30 -> 7h30 / 12h30 -> 14h30

Effectivement un composant Web de type time range picker c'est une bonne idée. ex :
https://codepen.io/bleriotnoguia/pen/OqOGaP

**Comment by xavax59** [comment]
Oui pour moi aussi à la demie heure ce serait mieux

**Comment by JC144** [comment]
Je vais creuser un peu plus pour la partie demi-heure, je n'avais pas prévu initialement.

Par contre, vous pouvez déjà tester avec un range à l'heure !

**Comment by xavax59** [comment]
Merci. Je vivais tester. Pour ne pas prendre en compte une plage HC on met 00:00 en debit et fin de période c’est bien ça ? 
concernant les HC chez moi c’est un peu bizarre 1:08 7:08. Et 12h38 14h38

Pour l’extraction enedis on peut choisir du 1 janvier 2023 au 31 décembre 2023 ? 
 Merci

**Comment by JC144** [comment]
Je vais rester sur des heures piles, l'impact sera minime pour quelques minutes. Je vais investiguer pour mettre en place à la demi-heure.

Pour Enedis, on peut remonter jusqu'à l'activation du suivi à la demi-heure (le calendrier devient grisé), j'ai un peu plus de 2 ans personnellement depuis leur site. Mais de temps en temps, l'export ne se fait pas.

**Comment by JC144** [comment]
Les HC/HP sont maintenant gérées à la minute.
Attention, vu que les exports sont à la demi-heure le plus souvent, il risque d'y avoir quelques légères différences.

**Comment by mxmrlt** [comment]
@JC144 Je reviens sur le sujet.
Les résultats sont plutôt pas mal et largement suffisants et fiables pour comparer.
Merci.

Et bravo à la communauté car je m’aperçois que ça a pas mal évolué cette dernière semaine.

Hâte (pas vraiment dans l'absolu) de simuler avec les nouvelles grilles tarifaires de début février.

**Comment by JC144** [comment]
Merci pour le retour, ça fait chaud au cœur !

La communauté a été folle et le projet a fait un bond en quelques jours.
