### ISSUE TITLE
Gestion des fichiers Enedis avec fréquence de 15min

### ISSUE THREAD

**Issue by odurecu** [JC144/EDF_Simulateur_Prix#20]
Bonjour,

Dans mes essais faits avec des fichiers Enedis, j'ai constaté une consommation calculée par le simulateur trop importante (le double)
Ce souci apparaît au moment où je suis passé sur un abonnement ZenFlex, ce qui a eu la particularité d'activer la collecte de mes données Linky avec un pas de 15 minutes.

Je joins un fichier correspondant pour vérifier si le problème vient bien de là

**Comment by JC144** [comment]
Bonjour,

J'ai téléchargé votre fichier et je l'ai anonymisé de mon côté, est-ce que vous pouvez le supprimer dès que vous voyez ce message.
Votre numéro de PDL est visible.

**Comment by JC144** [comment]
J'ai créé une branche de dev et j'ai poussé une 1ere version. Le site d'EDF est indisponible, je peux pas comparer de mon côté.

Est-ce que vous pouvez me dire si c'est + cohérents ? Normalement tous les types de pallier devraient être géré maintenant.

**Comment by odurecu** [comment]
Il y a une URL de sandbox où la branche dev est déployée pour tester ?

**Comment by JC144** [comment]
Pas pour le moment, il faut sélectionner la branche Dev depuis GitHub et récupérer le code en local, il suffit d'ouvrir le fichier index.html après, il y a rien à lancer.

**Comment by odurecu** [comment]
Test fait et résultat concluant. Il reste des écarts, peut-être dus à des cumuls d'arrondis journaliers ?
Sur 3 mois, le simulateur donne 520 / 505 / 462
La visu mensuelle Enedis donne 498 / 497 / 466

**Comment by JC144** [comment]
Hop !

Je pense que les dernières modifications devraient résoudre ce soucis.
Est-ce que pouvez réessayer à l'occasion ?

**Comment by odurecu** [comment]
Les totaux par mois sont corrects maintenant, cohérents avec les valeurs Enedis
Par contre, nouveau bug apparu : une ligne pour le 29/09 apparaît dans le simulateur alors que mon fichier début au 30/09.
Comme cette date n'existe pas dans mon export, le simulateur fait de la division par zéro sur ce jour là...
```
Jour | Consommation totale | Conso HC (kWh) | Estimation HC (€) | Conso HP (kWh) | Estimation HP (€) | Total (€)
2023/09/29 | InfinitykWh | InfinitykWh | Infinity€ | 0.00kWh | 0.00€ | Infinity€
```

ce qui plante les cumuls mensuel et total
```
Septembre
InfinitykWh / Infinity€
```

**Comment by JC144** [comment]
Curieux, je viens de tester avec différents fichiers, je ne constate pas.

Je veux bien votre fichier (comme d'habitude en supprimant le PDL dans le nom et à l'intérieur).

**Comment by odurecu** [comment]
Voici le fichier, ça le fait avec un autre. Quand les périodes ne débutent  pas en début de mois ?

[Enedis_Conso_Heure_20230930-20240118.csv](https://github.com/JC144/EDF_Simulateur_Prix/files/14053337/Enedis_Conso_Heure_20230930-20240118.csv)

**Comment by JC144** [comment]
![image](https://github.com/JC144/EDF_Simulateur_Prix/assets/1168432/9a0a4e4d-bfe5-4141-8c46-435b083af1bc)
J'ai bien la ligne en trop mais le mois n'est pas en erreur.

**Comment by odurecu** [comment]
Je continuais mes tests avec la branche dev. Sur le main, je viens de tester, effectivement les cumuls mensuel et total sont ok même s'il y a un jour en erreur
