### ISSUE TITLE
Quelques centimes de différences entre Tempo réel et simulation

### ISSUE THREAD

**Issue by JC144** [JC144/EDF_Simulateur_Prix#22]
A investiguer, le portail d'EDF m'affiche quelques centimes de différences.
A voir si c'est un soucis d'arrondis ou si on saute quelques pas.

**Comment by zdimension** [comment]
J'ai quelques différences (de l'ordre de 1 à 10 centimes sur une plage d'un jour) par-ci par-là entre le simulateur et EDF... mais ça ne vient pas du simulateur. En fait, je n'ai pas les mêmes valeurs entre le CSV d'Enedis et celui d'EDF.

Exemple le 10 septembre:
![image](https://github.com/JC144/EDF_Simulateur_Prix/assets/4533568/6f90cad2-1f00-4f39-8343-cb49dd08da10)

Là, pour le coup, je ne sais pas trop quoi faire...

**Comment by JC144** [comment]
Et est-ce que votre csv d'EDF importé dans le simulateur est cohérent avec les valeurs d'EDF ?

J'ai un léger décalage avec le mien.

**Comment by zdimension** [comment]
Après import du CSV d'EDF, meilleurs résultats mais toujours des erreurs; semblerait qu'il y ait un pb de calcul des HC/HP. J'ai corrigé ça sur ma branche

**Comment by JC144** [comment]
Erf, bien vu, je n'ai pas pensé au changement de jours.
En effet, l'idée était de prendre la toute première tranche isolée pour compléter la dernière.

Vous pouvez reprendre depuis le commit précédent.

**Comment by zdimension** [comment]
> Edit : Je veux bien voir votre approche, je ne suis pas sûr de comprendre. La 1ere tranche du tableau (00:00) est ajoutée au groupe des 23:00 et on aurait un calcul : "(conso 23:00+conso 23:15+conso 23:30+conso 23:45+conso 00:00) / 5" ?

Le tableau a la forme suivante (donc est dans l'ordre chronologique inverse) :
- 00:00 (consommation de 23h à minuit/fin de journée)
- 23:00 (consommation de 22h à 23h)
- 22:00 (...)
- 21:00
- ...
- 01:00 (consommation de minuit/début de journée à 1h)

Problème, c'est que la première, bien que postérieure à la deuxième, a une heure inférieure (0 < 23). Ça n'a pas trop de sens, mais c'est le prix à payer pour avoir une arithmétique modulo 24 😄 

En fait, ça casse surtout au niveau de Tempo par exemple, où pour savoir si une heure doit être comptée pour le jour précédent ou le jour suivant, je regarde si elle est < 6. En effet, si elle l'est alors c'est le jour d'avant, si elle est ≥ 6 c'est pour le jour d'après. Ici, la tranche d'heure zéro correspond... à la fin de journée.

Du coup, plutôt que d'attribuer aux tranches une heure correspondant à leur *fin*, je leur attribue une heure correspond à leur *début*. Ce qui revient à soustraire une heure. On obtient donc un tableau de la forme :
- 23:00 (consommation de 23h à minuit/fin de journée)
- 22:00 (consommation de 22h à 23h)
- 21:00 (...)
- 20:00
- ...
- 00:00 (consommation de minuit/début de journée à 1h)

Et là, d'un coup, on a bien un relation d'ordre dans les entrées du tableau. La première ligne a pour heure 23 et est bien postérieure à la deuxième (23 > 22) qui est postérieure à la troisième (22 > 21) etc.

Et donc la condition "heure < 6" donne bien la bonne condition pour Tempo.

Maintenant... je ne sais pas trop ce que ça donnerait avec les relevés qui donnent toutes les 15 min plutôt que toutes les 30 min, je n'ai pas de quoi tester.

**Comment by JC144** [comment]
J'ai repoussé sur dev une solution basée sur le travail de @ver2ter.

C'est + précis avec l'export d'EDF (toujours le soucis propre à Tempo), par contre sur Enedis on est moins bon vu que 00:00 n'est pas à la même position.
Je vais voir si je peux me modifier l'export d'Enedis pour manipuler les mêmes données dans le calculator.

**Comment by JC144** [comment]
![image](https://github.com/JC144/EDF_Simulateur_Prix/assets/1168432/133bf47c-246d-4479-9eca-b44727b49ba2)

Enedis a l'air d'avoir la logique que tu proposes.
On peut essayer une seconde passe sur l'un ou l'autre importer pour calculer le pas une fois qu'on sait combien de tranches horaires il y a dans les différents jours, tu en penses quoi ?

**Comment by JC144** [comment]
Apparemment le pas est lié à certains forfaits. Je suppose que si changement de forfait sur une année, on pourrait avoir un changement de pas.
Sauf si nouveau forfait = nouveau contrat et dans ce cas là nouvel export de 0...

J'ai un export en pas de 15, je dois pouvoir tester si besoin.

**Comment by JC144** [comment]
> Étonnant, chez moi EDF et Enedis renvoient les mêmes choses

AH ! En effet, les lignes sont les mêmes, c'est au moment de l'import que les données importées se décalent.
