### ISSUE TITLE
Problème de calcul heures creuses / pleines

### ISSUE THREAD

**Issue by ver2ter** [JC144/EDF_Simulateur_Prix#23]
Bonjour,

J'essaie de comprendre comment utiliser le paramétrage des HC/HP.

Mes plages HC/HP sont les suivantes
<img width="386" alt="image" src="https://github.com/JC144/EDF_Simulateur_Prix/assets/5261697/62fe008f-89ba-4d87-ae2e-59d7a5149513">

J'ai pris pour référence le contrat _EDF - Bleu Heures Creuses_ pour avoir la possibilité de paramétrer les plages HC/HP
J'ai essayé les combinaisons suivantes en arrondissant les horaires (donc 03:00/08:00 et 14:00/17:00) et en mettant la plage inutilisée à 00:00/00:00

DS + N, N + AM,  AM + DS

DS: Début de Soirée (Jour 1)
N: Nuit (Jour 2)
AM: Après Midi (Jour 2)

Le tableau de bord EDF m'indique ce cumul pour 2023-DEC-01
<img width="234" alt="image" src="https://github.com/JC144/EDF_Simulateur_Prix/assets/5261697/2de808ee-efc6-4d71-9cf0-3898d525188a">

Aucune des 3 combinaisons ne tombent sur les valeurs EDF

<img width="243" alt="image" src="https://github.com/JC144/EDF_Simulateur_Prix/assets/5261697/eb10627a-80f2-4182-8287-d9dafc09f021">

Est-ce une mauvaise utilisation de ma part ou une erreur dans l'outil ?

**Comment by JC144** [comment]
Merci pour le retour.

Est-ce que vous pouvez me faire un screenshot d'un jour depuis le
simulateur et du même depuis EDF (en kWh et €)?

J'ai quelques centimes d'erreurs pour le moment par jour, on travaille
dessus. Cela pourrait nous aider.

Pour le moment, les potentielles raisons :
* dernière heure non prise en compte (23h)
* un cumul d'arrondis
* on gère uniquement les heures entières (sans minutes) pour le moment. On
va fixer ça.

Le dim. 21 janv. 2024, 12:51, Michaël Schwinn ***@***.***> a
écrit :

**Comment by ver2ter** [comment]
Voici le screen de l'outil pour la journée du 2023/12/01

<img width="568" alt="image" src="https://github.com/JC144/EDF_Simulateur_Prix/assets/5261697/e58c3d7e-b239-4172-88cf-c075ce99cc95">

Et l'équivalent EDF

**kWh**
<img width="228" alt="image" src="https://github.com/JC144/EDF_Simulateur_Prix/assets/5261697/cb252171-5dce-4bd9-8b00-820dbdcde612">

**Eur**
<img width="224" alt="image" src="https://github.com/JC144/EDF_Simulateur_Prix/assets/5261697/d8308d6e-f509-4e3c-a272-ae61de1ed902">

**Comment by JC144** [comment]
Bonsoir,

Je comprends mieux. Le scénario dans ce cas, c'est bien N + AM :
DS : 00:00 - 00:00
N : 03:00 - 08:00
AM : 14:00 - 17:00

Je vais investiguer.

**Comment by JC144** [comment]
J'ai mis à jour, j'ai toujours un léger déficit en euros mais les kWh ont l'air bon sur mes données. Vous me direz.

**Comment by ver2ter** [comment]
Merci pour la réactivité.

Malheureusement les chiffres du simulteurs sont encore incorrects (cf ci-dessous).
En revanche, j'ai pu reconstituer les chiffres sur excel, ceux du simulateur (incorrects) et ceux attendus EDF/HelloWatt.

Les horaires du fichier EDF sèment la confusion. Quand il indique 03:00 il faut comprendre que ce sont les consommation de la plage 02h30 --> 03h00 . Donc exclure des HC .

Si l'aide est acceptée sur le projet je peux regarder le code dans la semaine et faire un pull request.
Je suppose que ça tourne autour de la ligne 81 de calculator.js

Simulateur EDF
![image](https://github.com/JC144/EDF_Simulateur_Prix/assets/5261697/f67787e9-3d70-4db1-a667-d2d2f961a83c)

Reconstitution Excel 
![image](https://github.com/JC144/EDF_Simulateur_Prix/assets/5261697/c97f92f9-b856-448f-8c00-79f34d7985f8)

**Comment by JC144** [comment]
Bien sûr, tout aide est bienvenue, 4 personnes ont déjà contribué aux améliorations ce week-end.

Je constate aussi ce décalage sur les heures creuses, le diagnostic me parait cohérent.
On a aussi une erreur qui a été remontée sur la gestion de la première plage de la journée (dernière chronologique).

**Comment by ver2ter** [comment]
Parfait, je regarde dès que je peux.

La branche que je vais créer devra partir de main ou de dev ?

**Comment by JC144** [comment]
Top merci !
Plutôt de "dev".

**Comment by ver2ter** [comment]
PR disponible #26 :)
