### ISSUE TITLE
Erreur, pas de consommation et estimation à 32€

### ISSUE THREAD

**Issue by SebPoint** [JC144/EDF_Simulateur_Prix#25]
Bonjour,

Merci pour l'outil qui a l'air très intéressant.
Mais j'ai un problème, je n'arrive pas obtenir l'estimation, je n'ai pas de consommation et j'ai une estimation à 32€ environ..
Pour info, j'ai un abonnement triphasé en 18kvA avec HP-HC (01h30/7h30 et 15h-17h)
Ci-joint export Enedis
Merci pour votre aide.

Seb
[Enedis_Conso_Heure_20220930-20240121_xxxxxxxx.csv](https://github.com/JC144/EDF_Simulateur_Prix/files/14011190/Enedis_Conso_Heure_20220930-20240121_xxxxxxxx.csv)

**Comment by JC144** [comment]
Merci pour le fichier, je vais tester.

On a eu plusieurs retours sur les imports d'Enedis aujourd'hui, j'essaye de regarder ça assez rapidement.

Attention, votre numéro de PDL est aussi présent dans le nom du fichier. Je vous laisse le renommer.

**Comment by SebPoint** [comment]
> Merci pour le fichier, je vais tester.
> 
> Sur a eu plusieurs retours sur les importations d'Enedis aujourd'hui, j'essaye de regarder ça assez rapidement.
> 
> Attention, votre numéro de PDL est également présent dans le nom du fichier. Je vous laisse le renommer.

ça fonctionne avec le fichier EDF sauf 1 journée dans l'année en erreur. Merci c'est top

**Comment by JC144** [comment]
Pas encore iso sur un export Enedis avec la conso réelle, mais il y a du mieux sur la version de ce matin !

**Comment by JC144** [comment]
Sur mes données, je suis iso avec le site d'EDF et un export Enedis 🍾
