### ISSUE TITLE
Coût plus élevé dans le simulateur que sur le site EDF

### ISSUE THREAD

**Issue by patoche83** [JC144/EDF_Simulateur_Prix#28]
Bonsoir, en utilisant la dernière version, il y a bien une amélioration sur le simulateur par rapport aux doublons, mais en regardant un peu plus en détail pour voir si déjà le simulateur me donne a qques eruros prêt le même coût/an que j'ai dans mon espace EDF. Ce n'est pas le cas.
Je me suis aperçu que jusqu'en Juillet 2023, le coût par mois (ou jour) donné par le simulateur pour un abonnement tarif bleu HC/HP et plus élevé de 5 à 10euros que sur les données sur le site d'EDF. A partir de Août 2023, le cout ets le même a qques centimes prêt.  Cela serait-il en rapport avec l'augmentation des tarifs en Août dernier ? Les kwh semblent pourtant les mêmes.

Je peux vous fournir le cvs au besoin.
Merci.

**Comment by JC144** [comment]
En effet, ça ressemble beaucoup au changement de tarif d'Août. C'est by design, on applique les tarifs actuels sur une consommation passée. On aura le même problème en février quand on va appliquer l'augmentation de tarifs.

Pour EDF, ils doivent se trouver assez facilement pour faire le calcul sur un jour ou deux différents pour vérifier.

**Comment by patoche83** [comment]
Bonjour, oui c’est ce que j’en ai déduit. Je sais que je dois déduire 150 à 200€. Mais comme le but du simulateur est de prendre la décision de passer sur une autre offre, principalement tempo dans mon cas, il faudrait mentionner que le simulateur utilise les tarifs les plus récents. Sinon je pense que certaines personnes vont mettre en doute l’utilité du simulateur ;)Merci et bon courage pour la suite ! Cela devrait intéresser du monde par ces temps de recherche d’économies financières et de la planète :)Le 22 janv. 2024 à 22:06, JC144 ***@***.***> a écrit :﻿
En effet, ça ressemble beaucoup au changement de tarif d'Août. C'est by design, on applique les tarifs actuels sur une consommation passée. On aura le même problème en février quand on va appliquer l'augmentation de tarifs.
Pour EDF, ils doivent se trouver assez facilement pour faire le calcul sur un jour ou deux différents pour vérifier.

**Comment by JC144** [comment]
Vous avez raison, je vais essayer de trouver une tournure adéquat pour expliquer ça.

Merci pour les encouragements ! 😉
