### ISSUE TITLE
Tarif EJP à zéro

### ISSUE THREAD

**Issue by Mathieu3878** [JC144/EDF_Simulateur_Prix#29]
Lors de ma simulation, les données EJP sont calculées à zéro et fausse donc les résultats.
J'ai fait plusieurs essais et j'ai systématiquement le même résultat.
Je met en PJ mon fichier de données et une copie d'écran de mon résultat pour faciliter la résolution du problème.

(https://github.com/JC144/EDF_Simulateur_Prix/files/14022335/Enedis_Conso_Heure_20230122-20240122_19334442740389.csv)
[Enedis_Conso_Heure_20230122-20240122.csv](https://github.com/JC144/EDF_Simulateur_Prix/files/14024271/Enedis_Conso_Heure_20230122-20240122.csv)

**Comment by JC144** [comment]
Bonjour,

Sur la dernière version votre fichier a l'air de marcher.
J'ai quand même fixé une typo dans le fichier.
Quel navigateur utilisez-vous ?

(Pensez à supprimer votre fichier CSV de votre message, le numéro PDL est visible).

**Comment by Mathieu3878** [comment]
J'ai modifié le fichier pour supprimer mon PDL et j'ai inscrit la nouvelle version dans le premier poste.
J'ai fait la simulation avec Edge en version 120.0.2210.91.
Avec le fix, j'obtiens bien des résultats pour EJP et tempo devient bien l'offre la plus probante dans mon cas.
Je suis déjà en tempo et je faisais juste un test pour voir le fonctionnement de votre site.
La simulation est top bravo et vous êtes super réactif en plus à la demande.

**Comment by JC144** [comment]
Merci pour les retours, ça m'a permis d'affiner :)

Bonne journée.

**Comment by marmotz** [comment]
j'ai moi aussi EJP à 0
![image](https://github.com/JC144/EDF_Simulateur_Prix/assets/932553/8f500f24-ef50-42f5-a5eb-9227f43e73fe)

Linux / Chrome 120.0.6099.224 (Build officiel) (64 bits)

[edf.csv](https://github.com/JC144/EDF_Simulateur_Prix/files/14025509/edf.csv)

**Comment by JC144** [comment]
![image](https://github.com/JC144/EDF_Simulateur_Prix/assets/1168432/6b19e1f9-42d6-48ca-be24-4ea0c87f7fa6)

Je viens de tester à l'instant avec votre fichier dans Chrome et Firefox avec la version en ligne actuellement.
Si vous ouvrez la console (F12), des erreurs s'affichent ?

**Comment by marmotz** [comment]
non, aucune erreur dans la console

Il semblerait que le problème vient du fait que j'ai changer pour 6kVA, quand je laisse 9kVA, j'ai pas le soucis

**Comment by JC144** [comment]
Ahah ! Il n'y a pas de tarifs 6kVA pour EJP, il faudra que je rajoute un message !

**Comment by Mathieu3878** [comment]
Effectivement lors du deuxième test, je n'ai pas mis 6 kVA. J'ai laissé 9 car j'ai été trop vite ! 
Cela explique que le problème ne se produisait plus.

J'ai supprimé les fichiers dans le premier post ! 
Cette fois, plus de nom de PDL ! 
[Enedis_Conso_Heure_20230122-20240122.csv](https://github.com/JC144/EDF_Simulateur_Prix/files/14028027/Enedis_Conso_Heure_20230122-20240122.csv)

**Comment by marmotz** [comment]
En tout cas merci pour cet outil, je viens de changer d'offre !

**Comment by BapRx** [comment]
Bonsoir, lorsque la puissance choisie est 6 kVA l'idéal serait de mettre un warning mais surtout de ne pas inclure la ligne EJP dans la colonne `Différence`, je ne sais pas si c'est facilement faisable
