### ISSUE TITLE
Doublons dans les fichiers EDF

### ISSUE THREAD

**Issue by bvalat** [JC144/EDF_Simulateur_Prix#3]
J'avais des résultats totalement faux sur certains jours.
Je viens de m'apercevoir que les export csv fournis par edf ont pour certains jours toutes les données en double...

Exemple : 
26/12/2023		
00:00:00	176	Réelle
00:00:00	176	Réelle
23:30:00	174	Réelle
23:30:00	174	Réelle
23:00:00	168	Réelle
23:00:00	168	Réelle
22:30:00	168	Réelle

Listes des quelques jours impactés (au cas où ce serait pas que moi) : 03/01/2024, 26/12/2023,20/12/2023,12/12/2024,10/12/2024,....

Je ne compte pas trop sur la réactivité d'EDF à corriger cela...
Possible de détecter ce genre de doublon et les filtrer dans votre code?
Merci d'avance.

**Comment by bvalat** [comment]
REM : Je vois que certaines données ne sont pas non plus pile sur une heure ou sa demis heure.
Exemple : 
13/09
12:30:00	262	Réelle
12:14:10	148	Réelle
12:00:00	270	Réelle

21/08
13:00:00	280	Réelle
12:30:00	280	Réelle
12:29:44	148	Réelle
12:00:00	238	Réelle
11:30:00	194	Réelle

Du coup il faudrait aussi filter ça...
Pas super fiable leur données à EDF....

**Comment by JC144** [comment]
Ah l'enfer !
C'est bon à savoir, merci pour le retour. Les doublons devraient être gérables.
Par contre, ceux là :
12:30:00 280 Réelle
12:29:44 148 Réelle
😕

Quand vous dites "Totalement faux", je suppose que c'était une surconsommation sur la synthèse finale ?
Le détail vous a aidé pour trouver le problème ?

**Comment by bvalat** [comment]
J'ai comparé le résultat des calculs avec les chiffres d'équilibre (le site d'edf) et la j'ai vu 37€ pour une journée à 19€
J'ai donc cherché ce qui n'allait pas. 
Et quitte à avoir ouvert le csv dans excel j'ai fait un filtre pour trouver les doublon sur 00;00;00 par exemple (pour trouver les jours avec deux lignes) et là j'ai vu les heure farfelue....

**Comment by patoche83** [comment]
Bonsoir, et premièrement merci pour ce simulateur. J'hésite à passer sur tempo, donc cela va peut être me permettre de passer le cap :) . Mais effectivement, il y a bien un soucis avec le fichier csv pris de chez edf. J'ai aussi des doublons. Lorsque j'ai fait une première simul, l'offre tempo est au même coût que mon coût actuel bleu Heures Creuses (facture qui date de 2 jours) et le coût Bleu HC donné par le simulateur est 400 euros plus cher. J'ai bien vérifier dans mon log de récupération de données de conso du linky que j'ai dans mon appli domotique Home Assistant. il y a des tranches de demie heure qui sont doublés dans le csv. Par example, le 13 Janvier 2024, tout est en double, 
Par contre il ne me semble pas y avoir des tranches d'heure ou demie heure farfelues, c'est bien pile toutes les demie heures. 

A+ Merci

**Comment by JC144** [comment]
Je vais me pencher sur les doublons aujourd'hui.

Par contre, essayez de faire remonter ce soucis à EDF. Ils l'ont peut être pas vu et seront content de pouvoir le corriger.
S'il y a des erreurs à ce niveau, il y en a peut-être ailleurs :/

**Comment by JC144** [comment]
Les doublons sont gérés !

@bvalat, quand vous avez ça :
12:30:00 280 Réelle
12:29:44 148 Réelle
12:00:00 238 Réelle

la période 12:30:00 sur le site d'EDF est de 280, 148 ou 428 ?

**Comment by bvalat** [comment]
L'espace client d'EDF est en maintenance...
Je regarderai quand il sera de nouveau dispo.
REM : Je retéléchargerai les datas au cas où cette maintenance aie changé quoi que ce soit au niveau export.
REM2: Je comparerai aussi les data depuis un export Enedis vu qu'on peut avoir les deux.

**Comment by bvalat** [comment]
LOL... Les données EDF sont différentes mais dans certains cas c'est pire .
Pour l'export Enedis je n'ai ni les doublons ni ces étrangetés. Les données ont l'air plus propres.

21/08/2023 : 
13:00:00	152	Réelle
12:30:00	214	Réelle
12:29:44	1420	Réelle
12:00:00	240	Réelle
11:30:00	240	Réelle

Oui 1420 c'est pas une typo.
D'après les graphes sur équilibre (relevé manuel en survolant les barre graphes)
13:00:00	0.08Kwh
12:30:00	0.11Kwh
12:00:00	0.12Kwh
11:30:00	0.12Kwh
Enedis (attention trier dans le sens inverse d'EDF) : 
21/08/2023	11:30:00+02:00	240
21/08/2023	12:00:00+02:00	240
21/08/2023	12:30:00+02:00	214
21/08/2023	13:00:00+02:00	152


Idem le 02/09 :  

19:00:00	656	Réelle
18:45:26	2350	Réelle
18:30:00	666	Réelle
équilibre 
19:00:00	0.33kwh	
18:30:00	0.33kwh
Enedis : 
2023-09-02T18:30:00+02:00	666
2023-09-02T19:00:00+02:00	656
Bref je pense qu'on peut considérer ces heures comme des anomalies et du coup filtrer tout ce qui n'est pas XX:00:00 ou XX:30:00.

Je vous propose à votre convenance de soit vous fournir mes données (mais uniquement en privé) soit de comparer les résultats EDF vs Enedis quand les filtres seront en place voir si on a enfin les mêmes résultats.

PS : Vous avez un contact EDF pour que leur remonte les bugs? Impossible de trouver l'info....

**Comment by JC144** [comment]
Alors, j'ai fixé les horaires sur un import EDF, je ne prends plus que les 00 et 30.
Est-ce que vous pouvez déjà retester ça ?

Pour le support, j'ai trouvé ça sur le site, il y a l'air d'y avoir un formulaire ou par téléphone : https://particulier.edf.fr/fr/accueil/electricite-gaz/choisir-edf/proximite-disponibilite.html
