### ISSUE TITLE
Plage HP/HC non prise en compte pour EDF bleu heures creuses

### ISSUE THREAD

**Issue by vdavy** [JC144/EDF_Simulateur_Prix#30]
Il y a une erreur sur la prise en compte des plages horaires HC sur EDF bleu heures creuses. Tout est calculé en HP :
![Capture d’écran du 2024-01-23 15-12-42](https://github.com/JC144/EDF_Simulateur_Prix/assets/1531837/bbb24700-9064-4529-828c-a15badfcb156)

Même bug constaté sur :
- TotalEnergie - Heures Eco
- EDF - Zen Week-End Plus HC
- EDF - Zen Week-End HC
- EDF - Vert Electrique Heures Creuses
- EDF - Zen Fixe Heures Creuses
- Octopus - Heures Creuses

C'est ballot parce que du coup c'est faux.
Pour le reste des offres, ça fonctionne correctement.

Ci joint mon export Enedis : 
[Enedis_Conso_Heure_20220427-20240122_xxxx.csv](https://github.com/JC144/EDF_Simulateur_Prix/files/14025274/Enedis_Conso_Heure_20220427-20240122_xxxx.csv)

Sinon, super boulot pour cet outil.

**Comment by JC144** [comment]
Attention, l'encodage de ce csv n'est pas bon, il faudra remplacer les virgules par des points virgules.

J'ai mis à jour les heures creuses en gérant à la demi-heure, ça devrait aussi corriger votre soucis.

Tenez-moi au courant, je clôturerai en fonction.

**Comment by vdavy** [comment]
Effectivement, la dernière MAJ corrige le problème de prise en compte des HC. C'est cohérent avec mon calcul enedis.

Merci
