### ISSUE TITLE
Import Total Energie divisé par deux

### ISSUE THREAD

**Issue by JC144** [JC144/EDF_Simulateur_Prix#31]
Apparemment, lors d'un import d'un fichier Total Energie, la synthèse est deux fois inférieure au réel.

Je me demande si les Slices sont pas divisées par 2, je suis preneur des retours.

**Comment by Timon-45** [comment]
Hello, 

Effectivement, j'ai la même.
En pj l'export Total et Enedis si ca peut aider pour que les deux match :)

PS : merci pour le projet, je viens de voir que même avec un plancher elec rayonnant, tempo me ferai gagner ~200€/an vs mon contrat HP/HC.

[123456789-NOM-PRENOM.csv](https://github.com/JC144/EDF_Simulateur_Prix/files/14055821/123456789-NOM-PRENOM.csv)
[Enedis_Conso_Heure_20220203-20240124_099999999999999.csv](https://github.com/JC144/EDF_Simulateur_Prix/files/14055822/Enedis_Conso_Heure_20220203-20240124_099999999999999.csv)

**Comment by JC144** [comment]
Top ! Merci pour l'export, je vais regarder ça !

Pensez à revérifier début février quand on aura mis à jour les tarifs. Il commence à y avoir des rumeurs que Tempo pourrait être le tarif subissant la plus forte augmentation.

**Comment by JC144** [comment]
Alors j'ai poussé quelque chose. C'est mieux mais on a toujours un gap important. Je suis vraiment pas fan de l'export de TotalEnergies.
C'est rigolo, parce qu'à coté de ça, celui d'Enedis est en pas de 10 minutes et est super précis.

J'espère que ça va pouvoir vous aider.

**Comment by bokub** [comment]
ça m'a l'air pas si mal, pour 2023 j'ai:
-  ça sur le site de total: 
    ![image](https://github.com/JC144/EDF_Simulateur_Prix/assets/17952318/8ab2e1a3-0ee2-4470-bd1c-6ce8d5176720)

- ça sur Enedis
    ![image](https://github.com/JC144/EDF_Simulateur_Prix/assets/17952318/8dc80d83-e68b-4ffa-9ba0-2127297bb832)

- et ça sur cet outil:
    ![image](https://github.com/JC144/EDF_Simulateur_Prix/assets/17952318/813b169d-64f0-414b-bad4-258b90815285)

OK c'est pas exactement les mêmes chiffres, mais y'a pas un rapport 2 non plus

**Comment by Timon-45** [comment]
Yes, c'est beaucoup mieux ! 

J'ai 1,5% d'écart sur les kWh entre total et enedis.

De mon coté, je partirait quand même sur les exports enedis en priorité.

**Comment by lbourdel** [comment]
voici le nouveau tarif
https://www.revolution-energetique.com/voici-les-nouveaux-prix-de-lelectricite-en-france-au-1%E1%B5%89%CA%B3-fevrier-2024/

Tempo : + 22,73 % pour la tranche d’heures creuses en jours bleus

Le gouvernement ne veut pas que les francais fassent des economies, ce sont des impots en moins !!!

**Comment by Benoit-lpv** [comment]
@bokub pouvez vous sélectionnez "décembre 2023" au lieu de "janvier 2024" dans l'outil pour être sûr de ne prendre en compte que 2023 ?

**Comment by JC144** [comment]
@lbourdel C'est ma mission de la semaine prochaine, refaire une passe sur les tarifs pour intégrer les mises à jour. La taxe est une stratégie pour rattraper le bouclier de l'an dernier. Mais ne va pas dans le sens de l'électrisation de nos usages si on voulait faire disparaître la dépendance aux énergies fossiles. Mais c'est le jeu.

@bokub, je veux bien aussi voir le résultat en s'arrêtant sur Décembre 2023. Normalement, la recherche inclus le mois de fin. C'est peut-être une erreur d'avoir fait ça.

**Comment by bokub** [comment]
Ah mince, effectivement je sais pas pourquoi mais j'ai supposé que le mois de fin était pas inclus...

Effectivement y'a un sacré décalage

| Import Enedis | Import Total |
|-----|------|
|  ![image](https://github.com/JC144/EDF_Simulateur_Prix/assets/17952318/ee7c6ef4-52e8-4a8b-98b3-d02c52b7cd1f) |   
![image](https://github.com/JC144/EDF_Simulateur_Prix/assets/17952318/38756fe8-a4df-498e-8234-1f00db2193cc)
 |

**Comment by Timon-45** [comment]
@bokub, attention, depuis mon compte total, je ne peux exporter plus d'une année : mon export du 24/01/2024 remonte jusqu'au 25/01/2023. Le delta vient peut être de la ?

**Comment by bokub** [comment]
Ah oui, mon CSV Total commence le 26 janvier 2023 et finit le 24 janvier 2024 !

Est-ce que ce serait pas mieux d'afficher des `<input type="date">` plutôt que ces menus déroulants "mois" et "année" ? Au moins on verrait bien la période

**Comment by JC144** [comment]
Mes tests étaient pas concluants, mais je suis pas contre une contre-proposition.
