### ISSUE TITLE
Enedis : option par heure indisponible

### ISSUE THREAD

**Issue by valgit** [JC144/EDF_Simulateur_Prix#34]
Sur le site Enedis, l'option "export par heure" est indisponible.

quelque chose a faire ?

**Comment by JC144** [comment]
Si ça dure, vous pouvez contacter leur support, j'avais eu le même soucis.

Vous pouvez aussi essayer d'exporter depuis le site de votre fournisseur.

**Comment by bokub** [comment]
J'avais ça aussi cet après-midi, avant de me rendre compte que ma collecte était désactivée !

Je viens de la remettre et j'ai toutes mes données horaires du passé qui sont devenues disponibles

C'est ce bouton, dans l'onglet "Gérer l'accès à mes données"

![image](https://github.com/JC144/EDF_Simulateur_Prix/assets/17952318/5b8ed3b4-93b7-4e80-9401-e2795d5711e5)

**Comment by valgit** [comment]
c'est quand même bête, je viens de voir qu'il y a 2 trucs :  
* activer l'enregistrement
* activer la collecte

a quoi sert d'enregistrer sans collecte ? bravo les gars de les GUI Enedis !
bref, ça veux aussi dire, que je ne peux pas avoir l'historique de l'année dernière pour une simu, snif !

**Comment by bokub** [comment]
> ça veux aussi dire, que je ne peux pas avoir l'historique de l'année dernière pour une simu

T'es sûr de toi ? Moi en activant la collecte j'ai eu accès à toutes les données du passé
