### ISSUE TITLE
Simulation uniquement avec les tranches quotidiennes

### ISSUE THREAD

**Issue by TontonJip** [JC144/EDF_Simulateur_Prix#36]
Bonjour,

Je découvre cette simulation et je vous remercie de la partager.

En suivant les tutos, je m'aperçois que Enedis relevait ma consommation quotidienne car la collecte horaire n'était pas activée (je l'ai activée ce jour).
Néanmoins, je souhaiterai pouvoir simuler ma consommation avec un forfait Tempo (jours bleu, blanc ou rouge) : pensez vous possible de réaliser cette étude avec ma consommation journalière sur 1 an en modifiant le simulateur ? En modifiant à peu près le fichier CSV de consommation quotidienne récupéré chez Enedis ?

D'avance, merci de votre retour,

**Comment by JC144** [comment]
Bonjour,

ça va être difficile de calculer un jour tempo. Les journées sont à cheval sur 2 jours réels (de 6h à 6h) avec des heures creuses et pleines derrière, il risque d'y avoir un sacré biais.

Après, ce que vous pouvez faire, c'est attendre un premier mois et le dupliquer sur l'année.
Ca ne sera pas idéal en fonction de vos appareils électriques mais ça peut vous donner une idée.

**Comment by TontonJip** [comment]
Merci de votre retour ! Je vais lancer ça sur 1 mois et suivre vos conseils.
Je suis vraiment dans l'interrogation personnelle des différentes solutions d'économies financière et écologique concernant ma consommation électrique (forfait Tempo, panneau solaire Plug&Play pour effacer le talon, panneaux solaires de production avec revente Enedis, etc). Cela nécessite beaucoup d'acquisition d'informations et ce n'est pas facile de s'y retrouver. Votre outil est justement un moyen simple et rapide de pouvoir comparer les différents forfaits d'abonnement pour commencer, mais il va falloir que je sois patient pour l'utiliser.

**Comment by JC144** [comment]
Gros sujet ! Cet article peut vous intéresser https://blog.spyou.org/wordpress-mu/2023/12/15/par-ici-lenergie/

Il y a une belle partie sur la réglementation et quelques astuces pour pas être embêté administrativement.

Ça parle aussi de revente et de coopérative énergétique. Tout en restant purement technique.
