### ISSUE TITLE
Différences de tarif entre les différents résultat

### ISSUE THREAD

**Issue by 10tribu** [JC144/EDF_Simulateur_Prix#4]
Ca serai sympa d'avoir la différence de cout entre tous les résultats de contrat

**Comment by JC144** [comment]
Actuellement ils sont triés du moins cher au plus cher.

C'est une bonne idée, je garde ça en tête. Vous souhaiteriez la différence entre chaque tarif et le moins cher par exemple ?

**Comment by JC144** [comment]
Ahah @BenoitGoimier a été plus rapide, c'est dispo, je clos !

**Comment by 10tribu** [comment]
Merci pour l'ajout de la différence c'est top et rapide !
Juste si je peux me permettre pour la dernière cellule de la ligne,
 il faudrait je pense ne rien afficher, 
 à la place de "+ 0.00 € TTC (0.00 €/mois)"
Ou afficher un texte du genre : "Contrat le moins cher !"

Bravo et merci en tout cas pour ce simulateur très utiles !

Ps : j'avais pas vu qu'au clic il y avais un collapse avec des données, 
peut être mettre un icône signifiant l'action du collapse du type (fontawesome) <i class="fa-solid fa-chevron-down"></i>
