### ISSUE TITLE
Erreur lors du calcul de la journée

### ISSUE THREAD

**Issue by mcmyst** [JC144/EDF_Simulateur_Prix#41]
Bonjour,

J'ai réalisé un téléchargement depuis le site ENEDIS que j'ai utilisé pour faire une simulation.
Le problème est que l'outil remonte des errerus de calcul sur la plupart des journées (pas toutes).
Le message indiqué est : Erreur lors du calcul de la journée

Voici le fichier sans le numéro de PDL; 

Merci pour votre aide.

**Comment by JC144** [comment]
Bonjour,

Je ne peux pas ouvrir votre fichier actuellement mais essayez de l'ouvrir dans un éditeur de fichiers texte (notepad++, visual studio code) et remplacez les virgules par des points virgules.

Je suppute une corruption par Excel mais peut-être que je me trompe.

**Comment by mcmyst** [comment]
Merci pour le retour, effectivement je n'avais pas vu que le PDL était dans le nom du fichier...
Effectivement LibreOffice à viré les ";" pour mettre des ","

En téléchargeant à nouveau le fichier et en l'uploadant sans l'ouvrir j'ai toujours les erreurs de calcul.
Voici le fichier ou je n'ai fait que retirer le PDL avec un Bloc-Note : [Enedis_Conso_Heure_20221231-20240101_PDL.csv](https://github.com/JC144/EDF_Simulateur_Prix/files/14073182/Enedis_Conso_Heure_20221231-20240101_PDL.csv)

Si vous avez une piste, je suis preneur !

Merci

**Comment by JC144** [comment]
Ah dans ce cas, j'essaierai de regarder demain soir. C'est curieux.

**Comment by JC144** [comment]
Ok, je vois, il y avait des créneaux sans valeurs qui mettaient le calculateur en erreur. J'ai fixé, ça devrait mieux marcher, vous me direz.

**Comment by mcmyst** [comment]
Je confirme tout est OK, merci pour la réactivité !
Merci pour ce super outil, j'en parle à tout mon entourage ;).
