### ISSUE TITLE
La belle energie

### ISSUE THREAD

**Issue by 01awolf** [JC144/EDF_Simulateur_Prix#46]
Bonjour aux devs

Bravo pour votre travail.
Je me demandais si vous pouviez rajouter la tarification de ce distributeur ?
https://labellenergie.fr/faq/ou-trouver-la-grille-tarifaire-la-bellenergie/

Merci !

**Comment by BenoitGoimier** [comment]
Hello,

L'abonnement Prudence (prix fixe sur 1 an) est déjà disponible.
Les abonnements Constance et Garance (prix fixé pendant 2 et 3 ans) n'ont pas était inclus car ils sont obligatoirement moins favorable dans le comparateur : Le prix du Kwh est le même mais les abonnements sont plus élevés. 

C'est une question de choix personnel en misant sur une augmentation général des tarifs d'électricité hors taxe. 

Si j'ai bien compris les petites lignes, en prenant un abonnement aujourd'hui, il y aura quand même un augmentation le 1er février car c'est une taxe qui augmente et non pas le TRV.

**Comment by 01awolf** [comment]
Merci pour votre réponse.
Il faudra probablement revoir pas mal d'abonnements au 1er Février et je risque de voir mon abon Zen Flex actuel devenir moins interessant que l'abonnement Prudence.
A suivre

**Comment by JC144** [comment]
La plupart des tarifs sont à jour.
Je me suis emballé j'ai rajouté Constance et Garance pour mettre en valeur le prix de l'abonnement.
