### ISSUE TITLE
Différence de prix mensuel éronnée

### ISSUE THREAD

**Issue by henriduflot** [JC144/EDF_Simulateur_Prix#54]
Bonjour,

Merci pour tous le travail réalisé sur cet outil !

J'ai noté un très léger dysfonctionnement sur l'affichage des résultats dans la colonne Diff avec le plus aventageux.

<img width="1004" alt="image" src="https://github.com/JC144/EDF_Simulateur_Prix/assets/90287522/10ed74f7-e6d9-40b9-a71d-c434722222fe">

Le calcul prend la différence en € et la divise par 12 mois plutôt que de comparer les prix mensuel des deux fournisseurs.
Dans mon exemple la différence mensuel entre le 1er et le 2eme fournisseur devrait etre de 0,64€ / mois au lieu de 0,20€ / mois.

**Comment by JC144** [comment]
Je regarde ça demain, merci pour le retour !

**Comment by JC144** [comment]
Fixé ! merci pour le retour
