### ISSUE TITLE
Consommation différente entre le site d'énédis et le simulateur

### ISSUE THREAD

**Issue by xavax59** [JC144/EDF_Simulateur_Prix#6]
Bonjour,
je voudrais faire une comparaison sur l'année 2023. J4ai téléchargé toutes mes données depuis le site d'énédis.
Lorsque j'importe le fichier et que je selectionne la période j'ai ceci 2692 khw: 
<img width="1319" alt="image" src="https://github.com/JC144/EDF_Simulateur_Prix/assets/54884656/69a7f5f9-fe21-460f-a24f-385695dbc4cb">
et sur le site d'enedis j'ai ceci 3771 kwh : 
<img width="889" alt="image" src="https://github.com/JC144/EDF_Simulateur_Prix/assets/54884656/50b81eda-b322-49d1-8c8f-5081b0b4fac2">
Qu'ai je loupé ? 
Lorsque je regarde mois par mois j'ai bien la conso sauf pour janvier et février 2023 sur le comparateur
<img width="1304" alt="image" src="https://github.com/JC144/EDF_Simulateur_Prix/assets/54884656/4cdd4e6f-000f-4e62-b0c2-83e81e33e67f">

pour tant ur enedis j'ai bien la conso
<img width="245" alt="image" src="https://github.com/JC144/EDF_Simulateur_Prix/assets/54884656/1685eb97-90d3-4510-a985-c369a35c2b39">

Merci

**Comment by JC144** [comment]
Intéressant, en ouvrant l'export csv d'Enedis, vous avez bien Janvier et février ?
Les autres mois sont cohérents ?

**Comment by xavax59** [comment]
Oui les autres mois ca correspond parfaitement. 
dans le fichier j'ai bien des données pour janvier et février 
<img width="397" alt="image" src="https://github.com/JC144/EDF_Simulateur_Prix/assets/54884656/3a297aa6-6ff2-4e07-ae09-782a1a320578">

**Comment by JC144** [comment]
Curieux.

En premier, est-ce que vous pouvez vérifier en retéléchargeant le fichier csv ? Je veux être sûr qu'il a pas été enregistré entre temps depuis Excel, il a tendance à modifier le format initial.

Ensuite, est-ce qu'il y aurait pas une valeur aberrante sur ces deux mois ?

Si c'est possible, est-ce que vous pouvez me partager juste ces deux mois ? Je les intègrerai dans un export pour tester.

**Comment by xavax59** [comment]
Je n'avais pas ouvert le fichier avant de l'importer dans le simulateur. JE vais refaire l'export enedis pour tester et vous envoyer les 2 mois. mais je les envoie ou ? directement ici ?

**Comment by JC144** [comment]
jeanch.vass@gmail.com

**Comment by JC144** [comment]
Top merci pour les données ! J'ai pu tester, ça doit marcher maintenant.
Certaines lignes n'avaient pas de données et ça provoquait une erreur sur la journée.

Forcément la consommation finale sera légèrement différente de la réelle en l'absence de données.
