### ISSUE TITLE
Question compteur classique

### ISSUE THREAD

**Issue by lyonelf** [JC144/EDF_Simulateur_Prix#60]
Bonjour,

Le csv fourni par EDF fait afficher une erreur de calcul pour la journée

Est ce normal et donc le tarif indiqué est quand même globalement bon ou faut il adapter le site aux données non Linky?

![image](https://github.com/JC144/EDF_Simulateur_Prix/assets/34097487/d5b03829-bc86-4cf7-8e53-6d74e5fd8868)

**Comment by JC144** [comment]
Parfois, des données sont manquantes sur la journée dans le csv.

S'il y a assez de données, l'ordre de grandeur devrait être juste.

**Comment by 01awolf** [comment]
Meme probleme, j'ai ouvert un ticket avant de voir qu'il va faire doublon

**Comment by JC144** [comment]
Ah ! Est-ce que vous pouvez me partager le csv en supprimant la mention du PDL à l'intérieur et dans le nom du fichier ?

Je n'ai pas d'erreurs sur mes données, ça me permettrait de gérer un nouveau cas.

**Comment by 01awolf** [comment]
Et voici le mien 
[ma-conso-quotidienne.csv](https://github.com/JC144/EDF_Simulateur_Prix/files/14140005/ma-conso-quotidienne.csv)

**Comment by lyonelf** [comment]
Non Linky,  EDF ne propose que 2 fichiers:

Ma conso mensuelle
Mes index elec

**Comment by JC144** [comment]
Il faudrait voir du côté d'Enedis dans ce cas là. Mais je pense que le suivi à la demi-heure n'est pas activé dans votre cas.
