### ISSUE TITLE
Erreur lors du calcul de la journée

### ISSUE THREAD

**Issue by 01awolf** [JC144/EDF_Simulateur_Prix#62]
Bonjour,

Avec les nouveaux tarifs et l'ajout de certains j'ai voulu relancer le simulateur.
J'ai le message suivant quand je clique sur le détail d'une offre : 
"Erreur lors du calcul de la journée"

Etes vous au courant ?
Merci

**Comment by JC144** [comment]
Faudra peut-être que je retire cet élément du rond "information" mais les fichiers à utiliser sont les suivants :
EDF : mes-puissances-atteintes-30min-XXXX.csv
Enedis : Enedis_Conso_Heure_DATEDEBUT-DATEFIN_XXXXX.csv
TotalEnergies : 0123456789-NOM-PRENOM.csv

**Comment by 01awolf** [comment]
Erreur de ma part, j'avais été plus attentif la première fois que j'ai utilisé votre simulateur il y a qq semaines.
Du coup j'ai un doute, que faut il renseigner dans les plages HC ?
Celles de son contrat actuel (je suis en zen flex et j'ai pris un belle augmentation) ou celles d'un futur contrat à venir ?
Merci encore pour tout ce travail

**Comment by bddq** [comment]
Bonjour. 

J'ai eu cette erreur car les données dans le CSV pour la journée en question ne sont pas complètes.
Dans mon cas, cette première journée de l'export CSV commence à 17h00. Elle est donc "incomplète" et l'ensemble des données ne peut être calculée. D'où l'erreur certainement.

Cdlt,
Benoit

**Comment by JC144** [comment]
> Elle est donc "incomplète" et l'ensemble des données ne peut être calculée. D'où l'erreur certainement.

Fort probable en effet, j'ai préféré l'indiquer en erreur plutôt que d'afficher une journée incohérente. Sur une heure, ce n'est pas gênant, mais on a eu des cas avec trop peu d'heures pour avoir un calcul pertinent. A voir, si ça nécessite d'être retravaillé.
