### ISSUE TITLE
Ajout d'un fournisseur

### ISSUE THREAD

**Issue by bddq** [JC144/EDF_Simulateur_Prix#63]
Bonjour,

J'habite dans la région de Strasbourg et nous avons uniquement un fournisseur d'électricité (monopole d'entreprise locale de distribution).
Je vais ajouter les tarifs de l'ELD pour pouvoir les comparer dans votre outil.

Comment voyez-vous la possibilité d'exclure les autre fournisseurs qui ne peuvent pas distribuer sur notre territoire de la liste des résultats (un menu déroulant avec la liste des territoires ELD; environ 13 en France je crois) ?
Sinon, voulez-vous laisser toute la liste et éventuellement identifier les fournisseurs ELD ?

Encore merci pour cet outil !
Benoit

**Comment by JC144** [comment]
Je pense que pour démarrer, les gens devront aller voir s'ils peuvent ou non prendre un ELD.

A terme, je vais commencer à étudier la possibilité de sélectionner les tarifs que l'on veut visualiser depuis l'écran de configuration.
