### ISSUE TITLE
Différence avec estimation ZenFlex EDF

### ISSUE THREAD

**Issue by Gandulf78** [JC144/EDF_Simulateur_Prix#76]
Bonjour. 
Le calcul de l'offre ZenFlex EDF donne un résultat bien plus élevé que celui de l'appli EDF. 
Par exemple le 12/02 EDF estime ma consommation totale à 1,52€ tandis que vous calculez 1,67€. 
Sur le mois de février EDF estime 25€ (6€ HP, 11€ HC, 7€ abonnement) du 1er au 14 tandis que votre calcul donne 36,46€. 
Vous estimez une consommation HP systématiquement plus élevée que la consommation HC ce qui me semble erronné (peut-être une inversion dans le filtre horaire?). 

[Enedis_Conso_Heure_20230531-20240214_50067238117598.csv](https://github.com/JC144/EDF_Simulateur_Prix/files/14302788/Enedis_Conso_Heure_20230531-20240214_50067238117598.csv)

**Comment by JC144** [comment]
Intéressant.

Est-ce que vous pouvez me faire une impression écran ou noter le détail de quelques jours d'exemples avec les HC / HP, la date, le prix et les kWh ?

Sur les heures Creuses on est bien sur du 20:00->08:00, 13:00->18:00 ?

Il faudra peut-être que je mette à jour les jours sobriétés.

**Comment by zifnab0** [comment]
Bonjour,

le bug est dans zenFlex.js

    hc: [{
        start: {hour:0, minute:0},
        end: {hour:8, minute:0}
    },
    {
        start: 13,
        end: 18
    },
    {
        start: {hour:20, minute:0},
        end: {hour:24, minute:0}
    }],

A remplacer par :

    hc: [{
        start: {hour:0, minute:0},
        end: {hour:8, minute:0}
    },
    {
        start: {hour:13, minute:0},
        end: {hour:18, minute:0}
    },
    {
        start: {hour:20, minute:0},
        end: {hour:24, minute:0}
    }],

De plus, comment déterminez vous les jours sobriété ?

**Comment by JC144** [comment]
Bien vu ! C'est corrigé.
Les jours sobriétés sont définis dans le fichier directement.
Les 1ers étaient basés sur les jours rouges tempo en l'absence d'historique, les derniers sont normalement basés sur le réel (une connaissance me fournit sa liste en l'absence d'API)

**Comment by Gandulf78** [comment]
Les 20 jours "sobriétés" sont différents des jours rouge Tempo. Ils ne sont publiés la veille qu'aux abonnés TempoZen au travers de l'application EDF (et envoyés par SMS). Il n'y a pour l'instant pas d'API EDF pour publier publiquement les dates. 
Avantage par rapport à Tempo, les plages d'heure creuse sont beaucoup plus vastes et fixes (entre 20h et 8h, entre 13h et 18h) ce que je trouve pratique pour s'organiser.

**Comment by JC144** [comment]
Bon, j'ai rationalisé les jours sobriétés pour en avoir 20 par année civile.

Après avoir échangé avec d'autres personnes, j'ai l'impression que les jours sobriétés ne sont pas les mêmes pour tout le monde. Et ça peut expliquer qu'ils ne soient pas visibles sur le site d'EDF. Je vais essayer d'avoir une confirmation.

Je ne compte pas gérer les jours bonus parce que ça dépend beaucoup de la nécessité de les connaître pour adapter sa consommation.

En l'état, le simulateur devrait quand même permettre d'avoir une idée relativement juste.

**Comment by JC144** [comment]
Oh ! en fait si, j'ai trouvé une API : https://particulier.edf.fr/services/rest/opm/getOPMStatut?dateRelevant=2024-01-10

Bon, j'essaierai de faire une passe à l'occasion.

**Comment by Gandulf78** [comment]
Top ! C'est documenté quelque part?

**Comment by zifnab0** [comment]
> Oh ! en fait si, j'ai trouvé une API : https://particulier.edf.fr/services/rest/opm/getOPMStatut?dateRelevant=2024-01-10
> 
> Bon, j'essaierai de faire une passe à l'occasion.

Comment avez vous trouvé ? J'ai cherché, mais je ne trouve aucune documentation concernant l'API de particulier.edf.fr

**Comment by zifnab0** [comment]
Autre erreur, les dates sobriété sont au format YYYY-MM-DD. Il faut qu'elles soient au format YYYY/MM/DD sinon elles ne sont pas prises en compte par `specialDay.lastDays.includes(day.date)`

**Comment by JC144** [comment]
> Comment avez vous trouvé ? J'ai cherché, mais je ne trouve aucune documentation concernant l'API de particulier.edf.fr

Une personne en ZenFlex m'a envoyé le call d'API du site.

> Autre erreur, les dates sobriété sont au format YYYY-MM-DD dans le tableau specialDays.lastDays. Il faut qu'elles soient au format YYYY/MM/DD sinon elles ne sont pas prises en compte par specialDay.lastDays.includes(day.date)

Mon mauvais, c'est fixé !
