### ISSUE TITLE
Tempo - Jour bleu au lieu de blanc ou rouge

### ISSUE THREAD

**Issue by henriduflot** [JC144/EDF_Simulateur_Prix#77]
Avec un export Enedis sur le mois de février, l'offre EDF Tempo sort 1ère du classement. Mais en y regardant d'un peu plus près le jour du 12/02 est vue comme un jour bleu et non un jour rouge. Le 13/02 est vue également comme un jour bleu et au lieu d'un blanc.

<img width="881" alt="image" src="https://github.com/JC144/EDF_Simulateur_Prix/assets/90287522/eb0e95ab-a79f-404e-b2be-d5d2a67e8792">

Je joins mon export enedis en PJ :
[Enedis.csv](https://github.com/JC144/EDF_Simulateur_Prix/files/14324310/Enedis.csv)

**Comment by JC144** [comment]
Fixé, les nouveaux tarifs arriveront qu'en Mars en fait.
