### ISSUE TITLE
Pas de réponse du site mais pas d'erreur non plus

### ISSUE THREAD

**Issue by vanaelsg** [JC144/EDF_Simulateur_Prix#79]
Lorsque je remplis les infos necessaires, (Puissance souscrite, Choix du jour Zen Plus, Choix des Heures Creuses pour le tarif Bleu HC), que je met le csv de "Vos données Linky" depuis Enedis ou depuis TotalEnergies, je clique alors sur "Simuler les différents tarifs", mais rien ne se passe (pas de chargement, ni de message d'erreur).
J'ai essayé en téléchargeant le projet depuis GitHub mais le meme problème se produit.
Une idée de ce qui se passe? :-)
Merci!

**Comment by JC144** [comment]
Bonjour,

Alors est-ce que vos fichiers correspondent à un format similaire à celui-là : ?
EDF : mes-puissances-atteintes-30min-XXXX.csv
Enedis : Enedis_Conso_Heure_DATEDEBUT-DATEFIN_XXXXX.csv
TotalEnergies : 0123456789-NOM-PRENOM.csv 

Il y a potentiellement un bug que je n'arrive pas à reproduire au niveau du nom de fichier. Est-ce que vous avez des caractères spéciaux dedans ou des tirets ?

Est-ce que le javascript n'est pas bloqué au niveau du navigateur ?

Y a-t-il des erreurs dans la console de développement (bouton F12) ?

N'hésitez pas à partager vos fichiers en supprimant l'information sur le PDL dans le nom du fichier et à l'intérieur.

**Comment by Galen-Titanium** [comment]
Je rencontre le meme probleme il me semble voici les infos que j'ai pu collecter 
![erreur_simul_tarif](https://github.com/JC144/EDF_Simulateur_Prix/assets/478914/c131d28b-4035-494e-b5cb-429b4c550f4b)
[111111111-miot-samuel.csv](https://github.com/JC144/EDF_Simulateur_Prix/files/14449917/111111111-miot-samuel.csv)

à disposition pour essayer d'avancer les choses 
je n'ai pas vu d'informations de pdl dans le fichier je ne sais pas si c'est normal

je suis chez total energies pour info

SaM

**Comment by Galen-Titanium** [comment]
Bon sans que je comprenne pourquoi cela a fini par fonctionner avec le fichier renommer tele que je l'ai envoyé etrange

**Comment by JC144** [comment]
Le fichier renommé a posé soucis ou il a marché de suite ?
Est-ce qu'il y avait des caractères spéciaux au départ ?

**Comment by Galen-Titanium** [comment]
pas de caractères spéciaux je vais refaire des essais en étant plus attentif

**Comment by GeoHolz** [comment]
J'ai eu le soucis car il y avait des espaces dans le nomp de fichier ( deux prenoms )
En enlevant les espaces, ça fonctionne

**Comment by JC144** [comment]
Je pense que j'ai fixé.
Il y avait un soucis si le nom était en minuscule, avec des caractères spéciaux, un espace ou un tiret.
Normalement, l'analyse du nom est meilleure maintenant et j'ai rajouté des instructions.

Je clos, n'hésitez pas à réouvrir si cela se produit toujours
