### ISSUE TITLE
Attention à ne plus référencer (temporairement) le fournisseur SWITCH

### ISSUE THREAD

**Issue by 01awolf** [JC144/EDF_Simulateur_Prix#80]
Bonjour chers devs et encore merci pour ce travail.

Voici une info importante je pense
https://www.jechange.fr/energie/chez-switch

**Comment by JC144** [comment]
J'ai retiré les tarifs pour le moment, je vais à terme mettre en place une partie "tarifs communautaires" pour bien différencié ceux qui sont supportés et mis à jour et ceux plutôt mis à jour par la communauté.
