### ISSUE TITLE
Erreur JS : Uncaught TypeError: monthData.days is undefined

### ISSUE THREAD

**Issue by JSteunou** [JC144/EDF_Simulateur_Prix#83]
Tentative de simulation toute simple avec les paramètres par défaut + CSV TotalEnergie

Il ne se passe rien côté simulateur, en ouvrant la console j'ai vu cette erreur

![image](https://github.com/JC144/EDF_Simulateur_Prix/assets/2323127/9dbbde2c-d0ad-413a-a0fe-47bac3f0ffa3)

**Comment by JC144** [comment]
Ca peut être lié à un jour mal formaté, est-ce que vous pouvez partager votre fichier csv en supprimant toutes références au PDL et à votre Nom/Prenom dans le nom de fichier et son contenu ?

**Comment by JC144** [comment]
Je pense que j'ai fixé.
Il y avait un soucis si le nom était en minuscule, avec des caractères spéciaux, un espace ou un tiret.
Normalement, l'analyse du nom est meilleure maintenant et j'ai rajouté des instructions.

Je clos, n'hésitez pas à réouvrir si cela se produit toujours

**Comment by JSteunou** [comment]
Désolé de la réponse tardive, j'ai toujours le souci, voici à quoi ressemble le début du fichier, toutes les lignes ont l'air bien formatées

```
Énergie;Date;Consommation
Électricité;"08/03/2023 00:30:00";"0.081 kWh"
Électricité;"08/03/2023 01:00:00";"0.082 kWh"
Électricité;"08/03/2023 01:30:00";"1.233 kWh"
```

**Comment by JC144** [comment]
Zut, et le nom du fichier ressemble à quoi ?

**Comment by JC144** [comment]
Il doit y avoir encore des soucis avec des accents. Si vous les enlevez, ça marche ?

**Comment by JSteunou** [comment]
non j'ai trouvé, c'est votre regex pour le parser total energie qui part du postulat que c'est forcément 10 chiffres alors que j'en ai 9 https://github.com/JC144/EDF_Simulateur_Prix/blob/9eec9c6659370f1777d5da6ccd820e9ec1c8c63a/scripts/main.js#L99
