### ISSUE TITLE
Sicae-ely

### ISSUE THREAD

**Issue by sebastienserre** [JC144/EDF_Simulateur_Prix#84]
Bonjour,
J'habite une commune ou le gestionnaire de réseau n'est pas Enedis, mais Sicae-ely. https://www.sicae-ely.fr/
Dans le menu "courbes de charge", ils me proposent seulement un excel de ce type.
[consommation_81403852721191_2024-03-01_2024-03-31 (1).xlsx](https://github.com/JC144/EDF_Simulateur_Prix/files/14571472/consommation_81403852721191_2024-03-01_2024-03-31.1.xlsx)

le simulateur ne semble pas le comprendre... que manquerait il ?

**Comment by JC144** [comment]
Bonjour,

Actuellement nous n'avons pas d'importer pour sicae.
Le fichier n'a pas l'air très complexe, et il serait assez facile de copier et modifier le parser de Total.
Mon soucis, c'est que c'est un fichier Excel, et ça va être embêtant à importer depuis le navigateur, est-ce que Sicae permet un export en CSV ?

**Comment by sebastienserre** [comment]
Non il n'y a pas de CVSV visiblement XLS ou txt... qui ressemble a ca..
[consommation_81403852721191_2024-03-01_2024-03-31 (3).txt](https://github.com/JC144/EDF_Simulateur_Prix/files/14628819/consommation_81403852721191_2024-03-01_2024-03-31.3.txt)

Avez vous un exemple de CSV qui'al faudrait ?
Il n'y a peut etre pas grand chose a faire pour obtenir le CSV a partir de l'excel.

**Comment by JC144** [comment]
Ah ben oui, tout simplement. 

Il faudra un export plus long, mais je l'ai formaté dans la structure de Total : 
[0123456789-serre-sebastien.csv](https://github.com/JC144/EDF_Simulateur_Prix/files/14670428/0123456789-serre-sebastien.csv)

**Comment by JC144** [comment]
N'hésitez pas à réouvrir le ticket si jamais vous avez un soucis.
