### ISSUE TITLE
fichier edf introuvable 

### ISSUE THREAD

**Issue by epitre** [JC144/EDF_Simulateur_Prix#90]
Bonjour,

Merci pour cette super app.

J'ai voulu la tester en téléchargeant les fichiers depuis mon compte EDF, mais ça n'a pas fonctionné car je n'ai pas le fichier attendu :/

PI : j'ai un contrat vert électrique week-end

Voici les fichiers que j'ai :

![image](https://github.com/JC144/EDF_Simulateur_Prix/assets/1972431/18d9744f-ff95-45ed-ad20-28233cb50b72)

**Comment by JC144** [comment]
Regardez si le suivi à la demi-heure est actif.
Vous pouvez aussi essayer de regarder sur le site d'Enedis si l'export est meilleur.

**Comment by epitre** [comment]
> Regardez si le suivi à la demi-heure est actif.

Où est-ce qu'on voit ça @JC144 ?

**Comment by JC144** [comment]
J'avais peur que vous demandiez 😅

Il me semble que c'était sur la partie "equilibre" du site d'EDF mais je ne me rappelle pas exactement.

Apparemment sur la page "Suivre sa consommation"

**Comment by epitre** [comment]
Merci. J'ai trouvé : 
![image](https://github.com/JC144/EDF_Simulateur_Prix/assets/1972431/84b0a6e3-83ac-45cf-84ef-60324a81f145)

Mais je ne pense pas que ce soit rétroactif, donc pas d'analyse pour moi :shrug: 

Je vais voir sur enedis.
