### ISSUE TITLE
Format DATA

### ISSUE THREAD

**Issue by kostonou** [JC144/EDF_Simulateur_Prix#94]
Hello !

merci pour ce projet qui semble prometteur !

Je tente d'intégrer un parser pour le fournisseur mint energie.

J'ai un peu de mal à retrouver quel est le format de la variable "data" qui contient les données fournisseurs retraités pour être utilisable dans le projet (le projet n'est pas typé).

Je souhaiterais savoir s'il est possible d'avoir soit le format attendu, soit un exemple de données csv d'un des fournisseurs disposant d'un parser ?
Je pourrais retro-engineerer le code pour retrouver le format, mais je me dis qu'un échange est plus sympa ;)

J'ai lu dans une autre issue la proposition d'avoir des classes de tests qui permettraient de justement pouvoir découvrir le format attendu.

Le CSV fourni par mint-energie est hyper light :

> "Category";"HP";"HC"
"du 11/10/23 au 21/10/23";40;58
"du 22/10/23 au 21/11/23";161;193
"du 22/11/23 au 21/12/23";378;307
"du 22/12/23 au 21/01/24";539;362
"du 22/01/24 au 21/02/24";308;243
"du 22/02/24 au 21/03/24";324;278
"du 22/03/24 au 21/04/24";234;257
"du 22/04/24 au 21/05/24";165;186
"du 22/05/24 au 21/06/24";76;154
"du 22/06/24 au 25/06/24";8;14
"du 26/06/24 au 21/07/24";64;113

Merci d'avance :)

**Comment by JC144** [comment]
Bonjour,

Ce fichier a l'air de représenter la consommation Heures Pleines / Heures creuses sur un mois.

Alors ça peut vous servir pour faire un calcul grosse louche en prenant les autres tarifs mais ça ne sera pas compatible avec ce site.

Pour réaliser les calculs on se base sur des exports à la demi-heure voire au quart d'heure pour pouvoir appliquer les tarifs Tempo ou des heures creuses particulières.

Peut-être que vous pouvez vous rapprocher du site d'Enedis pour voir si votre compteur autorise l'export à la demi-heure, l'activer le cas échéant ou générer votre export.

Peut-être que Mint propose aussi d'autres fichiers ?

N'hésitez pas si vous avez d'autres questions.

**Comment by kostonou** [comment]
Ah mais je me suis fourvoyé,
Je ne savais pas qu'il était possible de créer un compte enedis en parallèle de mon compte de fournisseur d'énergie.
Donc je vais pouvoir complètement faire cela sans bidouille de mon coté.

Merci pour ta réponse, je clos l'issue
